"""Browser automation tools using Playwright."""

from .browser_manager import BrowserManager
from .browser_tools import (
    browser_install,
    browser_navigate,
    browser_click,
    browser_type,
    browser_fill_form,
    browser_take_screenshot,
    browser_evaluate,
    browser_wait_for,
    browser_press_key,
    browser_hover,
    browser_select_option,
    browser_file_upload,
    browser_handle_dialog,
    browser_drag,
    browser_resize,
    browser_tabs,
    browser_navigate_back,
    browser_snapshot,
    browser_network_requests,
    browser_console_messages,
    browser_close,
)

__all__ = [
    "BrowserManager",
    "browser_install",
    "browser_navigate", 
    "browser_click",
    "browser_type",
    "browser_fill_form",
    "browser_take_screenshot",
    "browser_evaluate",
    "browser_wait_for",
    "browser_press_key",
    "browser_hover",
    "browser_select_option",
    "browser_file_upload",
    "browser_handle_dialog",
    "browser_drag",
    "browser_resize",
    "browser_tabs",
    "browser_navigate_back",
    "browser_snapshot",
    "browser_network_requests",
    "browser_console_messages",
    "browser_close",
]